# Change these first
owner: blahajsystems # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Site
    url: https://blahaj.system
  - name: Auth
    url: https://auth.blahaj.systems
  - name: Portainer
    url: https://portainer.blahaj.systems
  - name: JetBrains Space
    url: https://portainer.blahaj.systems
  - name: TeamCity
    url: https://ci.blahaj.systems
  - name: Jellyfin
    url: https://jellyfin.blahaj.systems

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.blahaj.systems
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status page for blahaj.sysems"
  introMessage: Yeah
  navbar:
    - title: Main
      href: https://blahaj.systems
    - title: Auth
      href: https://auth.blahaj.systems

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
